import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Customs Duty Explained — Assessment, Tariff Schedules & Binding Rulings 2026 | DutyDecoder",
    description: "How customs duty is assessed: tariff schedules, customs valuation methods, binding rulings, anti-dumping duties, and the full duty assessment lifecycle from classification to payment.",
    alternates: { canonical: "/customs-duty/" },
    keywords: ["customs duty", "customs duty assessment", "tariff schedule", "binding tariff ruling", "customs valuation", "anti-dumping duty", "countervailing duty", "customs duty 2026"],
    openGraph: { title: "Customs Duty Guide — Assessment, Valuation & Tariff Schedules", description: "The complete customs duty lifecycle from HS classification and valuation through to assessment, payment, and appeals.", url: "/customs-duty", type: "article" },
};

export default function CustomsDutyPage() {
    const sS: React.CSSProperties = { marginBottom: "2.5rem", paddingBottom: "2.5rem", borderBottom: "1px solid var(--border)" };
    const h2: React.CSSProperties = { fontSize: "1.5rem", fontWeight: 700, marginBottom: "1rem", color: "var(--foreground)" };
    const body: React.CSSProperties = { color: "var(--muted-foreground)", lineHeight: 1.85, fontSize: "1.05rem" };

    const sections = [
        { id: "what-is-customs-duty", heading: "What Is Customs Duty?", content: `<strong>Customs duty</strong> is a financial charge levied by a government on goods crossing its national border. While the term is often used interchangeably with "import duty," customs duty specifically refers to the charge assessed <strong>by customs authorities</strong> as part of the formal clearance process — it includes the legal framework of classification, valuation, and assessment that determines exactly how much you owe.<p style="margin-top:1rem;">Every country maintains a <strong>national tariff schedule</strong> — a comprehensive document listing every possible product classification alongside its duty rate. In the US, this is the <a href="https://hts.usitc.gov/" target="_blank" rel="dofollow">Harmonized Tariff Schedule (HTS)</a> maintained by the USITC. In the EU, it's the <a href="https://ec.europa.eu/taxation_customs/dds2/taric/taric_consultation.jsp" target="_blank" rel="dofollow">TARIC database</a>. In the UK, it's the <a href="https://www.trade-tariff.service.gov.uk/" target="_blank" rel="dofollow">UK Global Tariff</a>.</p>` },
        { id: "assessment-lifecycle", heading: "The Customs Duty Assessment Lifecycle", content: `<p>When goods arrive at a port of entry, customs duty is assessed through a structured process:</p><ol style="padding-left:1.5rem;margin-top:1rem;"><li style="margin-bottom:1rem;"><strong>Declaration:</strong> The importer (or their customs broker) files an import declaration specifying product description, HS code, country of origin, and declared value.</li><li style="margin-bottom:1rem;"><strong>Classification Verification:</strong> Customs officers verify that the declared <a href="/hs-code-lookup/">HS code</a> matches the actual goods. If there's a discrepancy, customs may re-classify — often resulting in higher duty.</li><li style="margin-bottom:1rem;"><strong>Valuation:</strong> Customs determines the <strong>transaction value</strong> (price actually paid) or applies alternative valuation methods if the transaction value isn't acceptable (WTO Customs Valuation Agreement).</li><li style="margin-bottom:1rem;"><strong>Duty Calculation:</strong> The applicable duty rate from the tariff schedule is applied to the assessed customs value.</li><li style="margin-bottom:1rem;"><strong>Payment &amp; Release:</strong> Duties are paid (or secured by bond), and goods are released into domestic commerce. In most countries, duty must be paid before goods leave customs control.</li><li><strong>Post-Clearance Audit:</strong> Customs authorities can audit declarations up to <strong>5 years after importation</strong> in most jurisdictions, and reassess duty if errors are found.</li></ol>` },
        { id: "valuation-methods", heading: "Customs Valuation Methods", content: `<p>The <a href="https://www.wto.org/english/tratop_e/cusval_e/cusval_info_e.htm" target="_blank" rel="dofollow">WTO Customs Valuation Agreement</a> establishes 6 hierarchical methods for determining the value on which duty is assessed:</p><ol style="padding-left:1.5rem;margin-top:1rem;"><li style="margin-bottom:0.75rem;"><strong>Transaction Value (Method 1):</strong> The price actually paid or payable. Used in ~95% of cases. This is the default and preferred method.</li><li style="margin-bottom:0.75rem;"><strong>Transaction Value of Identical Goods (Method 2):</strong> Value based on identical goods sold for export to the same country around the same time.</li><li style="margin-bottom:0.75rem;"><strong>Transaction Value of Similar Goods (Method 3):</strong> Same as Method 2 but using similar (not identical) goods.</li><li style="margin-bottom:0.75rem;"><strong>Deductive Value (Method 4):</strong> Based on the resale price in the importing country, working backwards to deduct margins and costs.</li><li style="margin-bottom:0.75rem;"><strong>Computed Value (Method 5):</strong> Based on the cost of production plus profit and general expenses.</li><li><strong>Fall-back Method (Method 6):</strong> Flexible application of Methods 1-5, used when none of the above work. Cannot be based on arbitrary or fictitious values.</li></ol>` },
        { id: "binding-rulings", heading: "Binding Tariff Rulings", content: `<p>If you're unsure how your product should be classified, you can request a <strong>Binding Tariff Ruling (BTR)</strong> from customs authorities. This is an official, legally binding classification decision that customs must honor at the time of import.</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li><strong>US:</strong> Request a <a href="https://www.cbp.gov/trade/rulings" target="_blank" rel="dofollow">CBP Ruling</a> — free of charge, typically takes 30-90 days. Valid for cross-referencing throughout US ports.</li><li><strong>EU:</strong> Apply for a <strong>Binding Tariff Information (BTI)</strong> decision — valid for 3 years across all 27 EU member states.</li><li><strong>UK:</strong> Request an <strong>Advance Tariff Ruling (ATR)</strong> from <a href="https://www.gov.uk/guidance/apply-for-an-advance-tariff-ruling" target="_blank" rel="dofollow">HMRC</a> — valid for 3 years.</li></ul><p style="margin-top:1rem;"><strong>When to request a ruling:</strong> For novel products, multi-component goods, products near chapter boundaries, or any item with a duty rate differential that materially impacts your landed cost. The ruling eliminates classification risk entirely.</p>` },
        { id: "special-duties", heading: "Special Customs Duties", content: `<p>Beyond standard tariff rates, customs authorities impose additional duties in specific circumstances:</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:1rem;margin:1.5rem 0;"><div style="background:rgba(239,68,68,0.06);border:1px solid rgba(239,68,68,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1rem;color:#ef4444;margin-bottom:0.5rem;">Anti-Dumping (AD)</strong><p style="font-size:0.9rem;margin:0;">Applied when foreign goods are sold below fair market value. Rates typically range from 10% to 250%+. Determined through formal investigations by <a href="https://www.cbp.gov/trade/priority-issues/antidumping-and-countervailing-duties" target="_blank" rel="dofollow">CBP</a> or equivalent.</p></div><div style="background:rgba(245,158,11,0.06);border:1px solid rgba(245,158,11,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1rem;color:#f59e0b;margin-bottom:0.5rem;">Countervailing (CVD)</strong><p style="font-size:0.9rem;margin:0;">Offsets foreign government subsidies that give exporters an unfair advantage. Calculated based on the subsidy amount.</p></div><div style="background:rgba(59,130,246,0.06);border:1px solid rgba(59,130,246,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1rem;color:#3b82f6;margin-bottom:0.5rem;">Safeguard Duties</strong><p style="font-size:0.9rem;margin:0;">Temporary tariffs to protect industries from sudden import surges. Applied under WTO rules (Article XIX GATT) with declining rates over time.</p></div><div style="background:rgba(168,85,247,0.06);border:1px solid rgba(168,85,247,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1rem;color:#a855f7;margin-bottom:0.5rem;">Retaliatory / Section 301</strong><p style="font-size:0.9rem;margin:0;">Punitive tariffs in trade disputes. US Section 301 tariffs on China added 7.5-25% on hundreds of billions in goods. These can change rapidly with political developments.</p></div></div>` },
        { id: "appeals", heading: "Disputing a Customs Duty Assessment", content: `<p>If you believe customs has incorrectly classified, valued, or assessed your goods, you have the right to appeal:</p><ul style="padding-left:1.5rem;margin-top:0.75rem;"><li style="margin-bottom:1rem;"><strong>US:</strong> File a <strong>Protest (19 CFR §174)</strong> within 180 days of liquidation. If denied, appeal to the <strong>U.S. Court of International Trade</strong>.</li><li style="margin-bottom:1rem;"><strong>EU:</strong> Appeal to the national customs authority first, then to the relevant national court. The <strong>Court of Justice of the EU (CJEU)</strong> handles questions of EU customs law interpretation.</li><li style="margin-bottom:1rem;"><strong>UK:</strong> Request a <strong>departmental review</strong> or appeal directly to the <strong>First-tier Tribunal (Tax Chamber)</strong>.</li></ul><p style="margin-top:1rem;">In all jurisdictions, you can pay the disputed duty under protest (securing release of your goods) while the appeal is pending. Interest is paid on any overpayment if the appeal succeeds.</p>` },
    ];

    const faqs = [
        { question: "What is the difference between customs duty and import duty?", answer: "The terms are often used interchangeably. Customs duty more precisely refers to the duty assessed as part of the formal customs clearance process, including classification verification and valuation. Import duty is the broader term for any tariff on imported goods." },
        { question: "How long does customs duty assessment take?", answer: "For straightforward shipments with correct documentation, assessment takes minutes. Complex cases involving classification disputes, valuation questions, or physical inspection can take days to weeks. Using a binding tariff ruling eliminates classification delays." },
        { question: "Can customs reject my declared value?", answer: "Yes. If customs suspects the declared value is artificially low (transfer pricing, under-invoicing), they can reject the transaction value and apply alternative valuation methods under the WTO Valuation Agreement. This typically results in higher duty." },
        { question: "What is a binding tariff ruling?", answer: "A legally binding classification decision from customs. Once issued, all customs ports in that jurisdiction must honor the ruling. It eliminates classification risk and is particularly valuable for novel products or goods with high duty differentials." },
        { question: "How far back can customs reassess duties?", answer: "Most countries allow post-clearance audits up to 3-5 years after importation. The US allows 5 years for duty reassessment. If fraud is suspected, there is typically no statute of limitations." },
    ];

    const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) };
    const bcJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": process.env.NEXT_PUBLIC_BASE_URL || "https://duty-decoder.com" }, { "@type": "ListItem", "position": 2, "name": "Customs Duty" }] };

    return (<>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(bcJsonLd) }} />
        <main style={{ maxWidth: "1100px", margin: "0 auto" }} role="main">
            <header style={{ background: "linear-gradient(135deg, rgba(99,102,241,0.06), rgba(59,130,246,0.04))", border: "1px solid var(--border)", borderRadius: "16px", padding: "clamp(1.5rem, 4vw, 2.5rem) clamp(1.25rem, 4vw, 3rem)", marginBottom: "2rem", textAlign: "center" }}>
                <nav aria-label="Breadcrumb" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", marginBottom: "1rem" }}><Link href="/" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none", fontWeight: 600 }}>Home</Link><span style={{ color: "var(--muted-foreground)", fontSize: "0.85rem" }}>›</span><span style={{ fontSize: "0.85rem", color: "var(--muted-foreground)" }}>Customs Duty</span></nav>
                <h1 style={{ fontSize: "clamp(1.5rem, 4vw, 2.5rem)", fontWeight: 800, margin: "0 0 1rem", color: "var(--foreground)", lineHeight: 1.2 }}>Customs Duty — Assessment, Valuation &amp; Tariff Schedules</h1>
                <p style={{ fontSize: "1.1rem", color: "var(--muted-foreground)", lineHeight: 1.6, margin: "0 auto", maxWidth: "800px" }}>The complete customs duty lifecycle: from HS classification and WTO-compliant valuation to binding rulings, special duties, and dispute resolution.</p>
            </header>
            <div className="content-sidebar-grid">
                <article aria-label="Customs duty guide">
                    {sections.map((s, i) => (<section key={`s-${i}`} id={s.id} style={{ ...sS, borderBottom: i < sections.length - 1 ? "1px solid var(--border)" : "none" }}><h2 style={h2}>{s.heading}</h2><div style={body} dangerouslySetInnerHTML={{ __html: s.content }} /></section>))}
                    <div role="banner" style={{ margin: "3rem 0", background: "linear-gradient(135deg, var(--accent), #6366f1)", borderRadius: "16px", padding: "2.5rem", textAlign: "center", boxShadow: "0 10px 30px rgba(99,102,241,0.15)" }}>
                        <h2 style={{ fontSize: "1.75rem", fontWeight: 800, color: "#fff", margin: "0 0 0.75rem" }}>Calculate Customs Duty Instantly</h2>
                        <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,0.85)", margin: "0 0 1.5rem" }}>Get exact duty, tax, and fee breakdowns for any product route.</p>
                        <Link href="/calculate/" style={{ display: "inline-block", background: "#fff", color: "var(--accent)", fontWeight: 700, padding: "1rem 2.5rem", borderRadius: "8px", textDecoration: "none", fontSize: "1.1rem" }}>Open Calculator →</Link>
                    </div>
                    <section id="faq" aria-label="FAQ" style={{ marginBottom: "3rem" }}><h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "1.5rem", color: "var(--foreground)" }}>Frequently Asked Questions</h2>
                        {faqs.map((f, i) => (<details key={`faq-${i}`} style={{ background: "var(--card)", padding: "1.25rem 1.5rem", borderRadius: "12px", border: "1px solid var(--border)", marginBottom: "0.85rem" }}><summary style={{ fontWeight: 600, cursor: "pointer", color: "var(--foreground)", fontSize: "1rem" }}>{f.question}</summary><div style={{ marginTop: "1rem", color: "var(--muted-foreground)", lineHeight: 1.75, fontSize: "0.95rem" }}>{f.answer}</div></details>))}
                    </section>
                </article>
                <aside aria-label="Quick links" style={{ position: "sticky", top: "100px", display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <section style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.5rem", boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)" }}><h3 style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--foreground)", marginBottom: "0.5rem" }}>Duty Calculator</h3><p style={{ fontSize: "0.9rem", color: "var(--muted-foreground)", marginBottom: "1.25rem", lineHeight: 1.5 }}>Calculate exact customs duties for any product.</p><Link href="/calculate/" style={{ display: "block", textAlign: "center", background: "var(--accent)", color: "#fff", fontWeight: 600, padding: "0.85rem 1rem", borderRadius: "8px", textDecoration: "none", fontSize: "0.95rem" }}>Open Calculator →</Link></section>
                    <nav aria-label="Related" style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "1rem" }}>Related Guides</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.6rem" }}><li><Link href="/import-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Duty Guide</Link></li><li><Link href="/import-tax/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Tax (VAT/GST)</Link></li><li><Link href="/tariff-rates/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Global Tariff Rates</Link></li><li><Link href="/hs-code-lookup/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>HS Code Lookup</Link></li><li><Link href="/customs-clearance/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Customs Clearance</Link></li></ul></nav>
                    <nav aria-label="Official sources" style={{ background: "rgba(34,197,94,0.04)", border: "1px solid rgba(34,197,94,0.15)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>Official Sources</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.5rem" }}><li><a href="https://www.cbp.gov/trade/rulings" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>CBP Rulings Database ↗</a></li><li><a href="https://www.wto.org/english/tratop_e/cusval_e/cusval_info_e.htm" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>WTO Valuation Agreement ↗</a></li><li><a href="https://hts.usitc.gov/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>USITC HTS Schedule ↗</a></li><li><a href="https://www.gov.uk/guidance/apply-for-an-advance-tariff-ruling" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>UK Advance Tariff Ruling ↗</a></li></ul></nav>
                    <nav aria-label="TOC" style={{ borderTop: "1px solid var(--border)", paddingTop: "1rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>On This Page</h3><ul style={{ listStyle: "none", padding: 0, margin: 0 }}>{sections.map((s, i) => (<li key={`t-${i}`} style={{ marginBottom: "0.4rem" }}><a href={`#${s.id}`} style={{ color: "var(--muted-foreground)", textDecoration: "none", fontSize: "0.85rem" }}>{s.heading}</a></li>))}<li style={{ marginTop: "0.75rem", paddingTop: "0.75rem", borderTop: "1px solid var(--border)" }}><a href="#faq" style={{ color: "var(--foreground)", fontWeight: 500, textDecoration: "none", fontSize: "0.85rem" }}>FAQs</a></li></ul></nav>
                </aside>
            </div>
        </main>
    </>);
}
