import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tariff Rates Explained — MFN, Preferential & How Rates Are Set 2026 | Duty Decoder",
    description: "Understand tariff rates: how they're set, MFN vs preferential rates, tariff escalation, rate lookup tools, and major FTA rate comparisons across 50+ countries.",
    alternates: { canonical: "/tariff-rates/" },
    keywords: ["tariff rates", "MFN tariff rate", "preferential tariff rate", "tariff schedule", "import tariff rates 2026", "tariff rate lookup", "FTA tariff rates", "customs tariff", "trade tariff"],
    openGraph: { title: "Tariff Rates — MFN, Preferential & FTA Rate Guide 2026", description: "How tariff rates are determined, where to look them up, and how FTAs can reduce your rate to zero.", url: "/tariff-rates", type: "article" },
};

export default function TariffRatesPage() {
    const sS: React.CSSProperties = { marginBottom: "2.5rem", paddingBottom: "2.5rem", borderBottom: "1px solid var(--border)" };
    const h2: React.CSSProperties = { fontSize: "1.5rem", fontWeight: 700, marginBottom: "1rem", color: "var(--foreground)" };
    const body: React.CSSProperties = { color: "var(--muted-foreground)", lineHeight: 1.85, fontSize: "1.05rem" };

    const sections = [
        { id: "what-are-tariff-rates", heading: "What Are Tariff Rates?", content: `A <strong>tariff rate</strong> is the percentage or fixed amount of duty charged on imported goods. Every country publishes a <strong>national tariff schedule</strong> — a comprehensive list of all possible product classifications (HS codes) alongside their corresponding duty rates. The tariff rate directly determines your <a href="/import-duty/">import duty</a> cost.<p style="margin-top:1rem;">Tariff rates are set through a combination of international negotiations (WTO rounds), bilateral agreements (FTAs), and domestic trade policy. They are one of the most powerful tools governments have for regulating trade flows, protecting industries, and generating revenue.</p>` },
        { id: "mfn-rates", heading: "MFN Rates — The Default Tariff", content: `<p>The <strong>Most Favoured Nation (MFN)</strong> rate is the default tariff rate that applies to all <a href="https://www.wto.org/english/thewto_e/whatis_e/tif_e/fact2_e.htm" target="_blank" rel="dofollow">WTO member nations</a>. Under WTO rules, if you grant a trade advantage (like a lower tariff) to one member, you must extend the same advantage to <strong>all WTO members</strong>.</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li><strong>What this means:</strong> MFN is the <em>highest</em> rate you'll normally face. FTA preferential rates go lower; MFN is the baseline.</li><li><strong>Non-WTO countries:</strong> Countries like North Korea or certain sanctioned nations may face rates higher than MFN (Column 2 rates in the US HTS).</li><li><strong>Bound vs. Applied:</strong> WTO members commit to a maximum "bound" rate — the actual "applied" MFN rate is often lower. For example, the EU's average bound rate is ~5%, but applied rates on many goods are 0-3%.</li></ul>` },
        { id: "preferential-rates", heading: "Preferential Rates — FTA Advantages", content: `<p>Countries that sign <strong>Free Trade Agreements</strong> enjoy reduced or zero duty rates on qualifying goods. This is the single most impactful way to legally reduce import costs.</p><div style="overflow-x:auto;margin:1.5rem 0;"><table style="width:100%;border-collapse:collapse;font-size:0.95rem;"><thead><tr style="border-bottom:2px solid var(--border);"><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Agreement</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Members</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Typical Benefit</th></tr></thead><tbody><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;"><a href="https://ustr.gov/trade-agreements/free-trade-agreements/united-states-mexico-canada-agreement" target="_blank" rel="dofollow" style="color:var(--accent);"><strong>USMCA</strong></a></td><td style="padding:0.75rem;">US, Mexico, Canada</td><td style="padding:0.75rem;">0% duty on qualifying goods</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;"><a href="https://www.dfat.gov.au/trade/agreements/in-force/cptpp" target="_blank" rel="dofollow" style="color:var(--accent);"><strong>CPTPP</strong></a></td><td style="padding:0.75rem;">11 nations (UK, Japan, Canada, Australia...)</td><td style="padding:0.75rem;">Phased duty elimination</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;"><strong>RCEP</strong></td><td style="padding:0.75rem;">15 Asia-Pacific nations</td><td style="padding:0.75rem;">Gradual tariff reduction over 20 years</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;"><strong>EU Single Market</strong></td><td style="padding:0.75rem;">27 EU member states</td><td style="padding:0.75rem;">Zero internal tariffs</td></tr><tr><td style="padding:0.75rem;"><strong>AfCFTA</strong></td><td style="padding:0.75rem;">54 African nations</td><td style="padding:0.75rem;">90% tariff elimination by 2030</td></tr></tbody></table></div><p><strong>To claim preferential rates,</strong> you need a valid Certificate of Origin proving goods meet the agreement's Rules of Origin (ROO) — typically a minimum local content threshold or a tariff shift requirement.</p>` },
        { id: "tariff-escalation", heading: "Tariff Escalation — Why Processed Goods Cost More", content: `<p>A common pattern in global tariff policy is <strong>tariff escalation</strong> — where raw materials face low or zero duty, while processed goods face progressively higher rates:</p><div style="overflow-x:auto;margin:1.5rem 0;"><table style="width:100%;border-collapse:collapse;font-size:0.95rem;"><thead><tr style="border-bottom:2px solid var(--border);"><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Product Stage</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Example</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Typical US Duty</th></tr></thead><tbody><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Raw material</td><td style="padding:0.75rem;">Raw cotton</td><td style="padding:0.75rem;">0%</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Semi-processed</td><td style="padding:0.75rem;">Cotton yarn</td><td style="padding:0.75rem;">3-6%</td></tr><tr><td style="padding:0.75rem;">Finished goods</td><td style="padding:0.75rem;">Cotton shirt</td><td style="padding:0.75rem;">12-20%</td></tr></tbody></table></div><p>This pattern encourages developing countries to export raw materials rather than finished goods — a long-standing point of contention in WTO negotiations. It directly affects sourcing decisions: importing unfinished goods and processing domestically can be significantly cheaper than importing finished products.</p>` },
        { id: "lookup-tools", heading: "Where to Look Up Tariff Rates", content: `<p>Every major trading nation publishes its tariff schedule online. The key tools are:</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li style="margin-bottom:1rem;"><strong>🇺🇸 United States:</strong> <a href="https://hts.usitc.gov/" target="_blank" rel="dofollow">USITC HTS Online</a> — search by keyword or HS code. Includes all general, special, and column 2 rates, plus anti-dumping and countervailing duty orders.</li><li style="margin-bottom:1rem;"><strong>🇪🇺 European Union:</strong> <a href="https://ec.europa.eu/taxation_customs/dds2/taric/taric_consultation.jsp" target="_blank" rel="dofollow">TARIC database</a> — search by commodity code. Shows MFN rates, preferential rates by origin country, anti-dumping measures, and suspensions.</li><li style="margin-bottom:1rem;"><strong>🇬🇧 United Kingdom:</strong> <a href="https://www.trade-tariff.service.gov.uk/" target="_blank" rel="dofollow">UK Trade Tariff</a> — lookup by commodity code or product description. Includes UK-specific post-Brexit rates, CPTPP rates, and supplementary units.</li><li style="margin-bottom:1rem;"><strong>🇨🇦 Canada:</strong> <a href="https://www.cbsa-asfc.gc.ca/trade-commerce/tariff-tarif/" target="_blank" rel="dofollow">CBSA Customs Tariff</a> — includes MFN, GPT (General Preferential Tariff), and preferential rates.</li><li style="margin-bottom:1rem;"><strong>🇯🇵 Japan:</strong> <a href="https://www.customs.go.jp/english/tariff/" target="_blank" rel="dofollow">Japan Customs Tariff Schedule</a></li><li><strong>🌐 WTO Tariff Database:</strong> <a href="https://tao.wto.org/" target="_blank" rel="dofollow">WTO TAO</a> — allows cross-country tariff comparisons for any HS code across all WTO members.</li></ul>` },
        { id: "rate-changes", heading: "How Tariff Rates Change", content: `<p>Tariff rates are not static. They change through several mechanisms:</p><ul style="padding-left:1.5rem;margin-top:0.75rem;"><li style="margin-bottom:1rem;"><strong>Annual Budget/Finance Acts:</strong> Countries often adjust rates in their annual budget. Pakistan, for example, frequently changes rates through <a href="https://www.fbr.gov.pk/customs-tariff/131253" target="_blank" rel="dofollow">SROs (Statutory Regulatory Orders)</a> multiple times per year.</li><li style="margin-bottom:1rem;"><strong>FTA Phasing Schedules:</strong> Many FTAs don't go to 0% overnight. They have 5, 10, or 20-year phasing schedules where rates decrease gradually. RCEP, for example, phases out tariffs over 20 years.</li><li style="margin-bottom:1rem;"><strong>Trade Disputes:</strong> Retaliatory tariffs can appear suddenly. US Section 301 tariffs on China were imposed with just weeks of notice, adding 25% overnight.</li><li style="margin-bottom:1rem;"><strong>HS Revision Cycles:</strong> Every 5 years, the WCO revises the HS system. This can cause codes to split, merge, or renumber — changing the applicable rate even if the product hasn't changed.</li><li><strong>Temporary Suspensions:</strong> The EU frequently grants temporary duty suspensions on inputs not produced domestically. These are reviewed bi-annually.</li></ul>` },
    ];

    const faqs = [
        { question: "What is the average tariff rate globally?", answer: "The global weighted average MFN tariff is approximately 5-6% for industrial goods and 15-20% for agricultural products, though this varies enormously by country and product. Some goods face 0% duty; others face 300%+." },
        { question: "Where can I look up tariff rates for free?", answer: "Every country publishes its tariff schedule online for free. Key tools include USITC HTS (US), TARIC (EU), UK Trade Tariff (UK), and the WTO TAO database for cross-country comparisons." },
        { question: "How do I get a lower tariff rate?", answer: "Claim preferential rates under applicable Free Trade Agreements with a valid Certificate of Origin. Other strategies include tariff engineering, Foreign Trade Zones, and duty drawback on re-exports." },
        { question: "What happens if the tariff rate changes after I ship?", answer: "The duty rate that applies is the rate in effect on the date of importation (when goods enter customs territory), not the date of shipping or the date of purchase. Monitor rate changes before shipping." },
        { question: "Why does the same product have different rates in different countries?", answer: "Each country sets its own national tariff rates based on trade policy, industrial protection needs, and WTO commitments. The HS code is international, but the duty rate is entirely national." },
    ];

    const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) };
    const bcJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": process.env.NEXT_PUBLIC_BASE_URL || "https://duty-decoder.com" }, { "@type": "ListItem", "position": 2, "name": "Tariff Rates" }] };

    return (<>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(bcJsonLd) }} />
        <main style={{ maxWidth: "1100px", margin: "0 auto" }} role="main">
            <header style={{ background: "linear-gradient(135deg, rgba(99,102,241,0.06), rgba(59,130,246,0.04))", border: "1px solid var(--border)", borderRadius: "16px", padding: "clamp(1.5rem, 4vw, 2.5rem) clamp(1.25rem, 4vw, 3rem)", marginBottom: "2rem", textAlign: "center" }}>
                <nav aria-label="Breadcrumb" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", marginBottom: "1rem" }}><Link href="/" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none", fontWeight: 600 }}>Home</Link><span style={{ color: "var(--muted-foreground)", fontSize: "0.85rem" }}>›</span><span style={{ fontSize: "0.85rem", color: "var(--muted-foreground)" }}>Tariff Rates</span></nav>
                <h1 style={{ fontSize: "clamp(1.5rem, 4vw, 2.5rem)", fontWeight: 800, margin: "0 0 1rem", color: "var(--foreground)", lineHeight: 1.2 }}>Tariff Rates — MFN, Preferential &amp; FTA Rate Guide</h1>
                <p style={{ fontSize: "1.1rem", color: "var(--muted-foreground)", lineHeight: 1.6, margin: "0 auto", maxWidth: "800px" }}>How tariff rates are determined, where to look them up for free, and how Free Trade Agreements can reduce your duty rate to zero.</p>
            </header>
            <div className="content-sidebar-grid">
                <article aria-label="Tariff rates guide">
                    {sections.map((s, i) => (<section key={`s-${i}`} id={s.id} style={{ ...sS, borderBottom: i < sections.length - 1 ? "1px solid var(--border)" : "none" }}><h2 style={h2}>{s.heading}</h2><div style={body} dangerouslySetInnerHTML={{ __html: s.content }} /></section>))}
                    <div role="banner" style={{ margin: "3rem 0", background: "linear-gradient(135deg, var(--accent), #6366f1)", borderRadius: "16px", padding: "2.5rem", textAlign: "center", boxShadow: "0 10px 30px rgba(99,102,241,0.15)" }}>
                        <h2 style={{ fontSize: "1.75rem", fontWeight: 800, color: "#fff", margin: "0 0 0.75rem" }}>Calculate Duties at Actual Rates</h2>
                        <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,0.85)", margin: "0 0 1.5rem" }}>Our calculator uses official 2026 tariff rates for 50+ countries.</p>
                        <Link href="/calculate/" style={{ display: "inline-block", background: "#fff", color: "var(--accent)", fontWeight: 700, padding: "1rem 2.5rem", borderRadius: "8px", textDecoration: "none", fontSize: "1.1rem" }}>Open Calculator →</Link>
                    </div>
                    <section id="faq" aria-label="FAQ" style={{ marginBottom: "3rem" }}><h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "1.5rem", color: "var(--foreground)" }}>Frequently Asked Questions</h2>{faqs.map((f, i) => (<details key={`faq-${i}`} style={{ background: "var(--card)", padding: "1.25rem 1.5rem", borderRadius: "12px", border: "1px solid var(--border)", marginBottom: "0.85rem" }}><summary style={{ fontWeight: 600, cursor: "pointer", color: "var(--foreground)", fontSize: "1rem" }}>{f.question}</summary><div style={{ marginTop: "1rem", color: "var(--muted-foreground)", lineHeight: 1.75, fontSize: "0.95rem" }}>{f.answer}</div></details>))}</section>
                </article>
                <aside aria-label="Quick links" style={{ position: "sticky", top: "100px", display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <section style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.5rem", boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)" }}><h3 style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--foreground)", marginBottom: "0.5rem" }}>Rate Calculator</h3><p style={{ fontSize: "0.9rem", color: "var(--muted-foreground)", marginBottom: "1.25rem", lineHeight: 1.5 }}>See the exact rate for your product and route.</p><Link href="/calculate/" style={{ display: "block", textAlign: "center", background: "var(--accent)", color: "#fff", fontWeight: 600, padding: "0.85rem 1rem", borderRadius: "8px", textDecoration: "none", fontSize: "0.95rem" }}>Open Calculator →</Link></section>
                    <nav aria-label="Related" style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "1rem" }}>Related Guides</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.6rem" }}><li><Link href="/import-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Duty Guide</Link></li><li><Link href="/customs-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Customs Duty Guide</Link></li><li><Link href="/hs-code-lookup/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>HS Code Lookup</Link></li><li><Link href="/import-tax/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Tax (VAT/GST)</Link></li><li><Link href="/import-restrictions/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Restrictions</Link></li></ul></nav>
                    <nav aria-label="Official sources" style={{ background: "rgba(34,197,94,0.04)", border: "1px solid rgba(34,197,94,0.15)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>Official Tariff Databases</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.5rem" }}><li><a href="https://hts.usitc.gov/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>USITC HTS Online ↗</a></li><li><a href="https://ec.europa.eu/taxation_customs/dds2/taric/taric_consultation.jsp" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>EU TARIC Database ↗</a></li><li><a href="https://www.trade-tariff.service.gov.uk/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>UK Trade Tariff ↗</a></li><li><a href="https://tao.wto.org/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>WTO TAO Database ↗</a></li></ul></nav>
                    <nav aria-label="TOC" style={{ borderTop: "1px solid var(--border)", paddingTop: "1rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>On This Page</h3><ul style={{ listStyle: "none", padding: 0, margin: 0 }}>{sections.map((s, i) => (<li key={`t-${i}`} style={{ marginBottom: "0.4rem" }}><a href={`#${s.id}`} style={{ color: "var(--muted-foreground)", textDecoration: "none", fontSize: "0.85rem" }}>{s.heading}</a></li>))}<li style={{ marginTop: "0.75rem", paddingTop: "0.75rem", borderTop: "1px solid var(--border)" }}><a href="#faq" style={{ color: "var(--foreground)", fontWeight: 500, textDecoration: "none", fontSize: "0.85rem" }}>FAQs</a></li></ul></nav>
                </aside>
            </div>
        </main>
    </>);
}
