import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Import Restrictions — Prohibited Goods, Quotas & Licensing 2026 | DutyDecoder",
    description: "Understand import restrictions: prohibited goods, restricted items requiring licenses, quotas, embargoes, dual-use controls, and country-specific import bans for 2026.",
    alternates: { canonical: "/import-restrictions/" },
    keywords: ["import restrictions", "prohibited imports", "restricted goods", "import quota", "import license", "trade embargo", "dual-use goods", "import ban", "customs restrictions 2026"],
    openGraph: { title: "Import Restrictions — Prohibited Goods, Licensing & Controls", description: "What you can't import, what needs special licenses, and who sets the rules: quotas, embargoes, dual-use controls, and country-specific import bans.", url: "/import-restrictions", type: "article" },
};

export default function ImportRestrictionsPage() {
    const sS: React.CSSProperties = { marginBottom: "2.5rem", paddingBottom: "2.5rem", borderBottom: "1px solid var(--border)" };
    const h2: React.CSSProperties = { fontSize: "1.5rem", fontWeight: 700, marginBottom: "1rem", color: "var(--foreground)" };
    const body: React.CSSProperties = { color: "var(--muted-foreground)", lineHeight: 1.85, fontSize: "1.05rem" };

    const sections = [
        { id: "what-are-restrictions", heading: "What Are Import Restrictions?", content: `<strong>Import restrictions</strong> are government-imposed controls that limit, regulate, or prohibit the importation of certain goods. Unlike tariffs (which impose a financial cost), restrictions can <strong>completely prevent</strong> goods from entering a country — regardless of your willingness to pay duty.<p style="margin-top:1rem;">Restrictions exist for reasons of <strong>national security</strong> (weapons, encryption technology), <strong>public health</strong> (drugs, contaminated food), <strong>environmental protection</strong> (endangered species, hazardous chemicals), <strong>public morals</strong> (banned literature, counterfeit goods), and <strong>economic policy</strong> (quotas to protect domestic industries).</p><p style="margin-top:1rem;">Customs authorities like <a href="https://www.cbp.gov/" target="_blank" rel="dofollow">US CBP</a> work alongside partner agencies — FDA, EPA, CPSC, USDA, ATF, and others — to enforce these restrictions at the border.</p>` },
        { id: "prohibited-vs-restricted", heading: "Prohibited vs. Restricted Goods", content: `<p>There's a critical difference between <strong>prohibited</strong> and <strong>restricted</strong> imports:</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem;margin:1.5rem 0;"><div style="background:rgba(239,68,68,0.06);border:1px solid rgba(239,68,68,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1.1rem;color:#ef4444;margin-bottom:0.5rem;">🚫 Prohibited Goods</strong><p style="font-size:0.9rem;margin:0;">Cannot be imported under <strong>any circumstances</strong>. Examples: counterfeit goods, child exploitation material, products violating intellectual property laws, and goods from comprehensively sanctioned countries (OFAC SDN list).</p></div><div style="background:rgba(245,158,11,0.06);border:1px solid rgba(245,158,11,0.15);border-radius:12px;padding:1.25rem;"><strong style="display:block;font-size:1.1rem;color:#f59e0b;margin-bottom:0.5rem;">⚠️ Restricted Goods</strong><p style="font-size:0.9rem;margin:0;"><strong>Can be imported</strong> but require prior authorization — import licenses, permits, certificates, or compliance with specific standards. Examples: firearms, pharmaceuticals, food products, chemicals, and endangered species products (CITES).</p></div></div>` },
        { id: "common-restrictions", heading: "Common Categories of Restricted Imports", content: `<ul style="padding-left:1.5rem;"><li style="margin-bottom:1.25rem;"><strong>Food &amp; Agricultural Products:</strong> Subject to FDA (US), FSA (UK), or EFSA (EU) standards. Require health certificates, phytosanitary certificates, and compliance with Maximum Residue Levels (MRLs) for pesticides. Some products face outright bans from specific countries due to disease outbreaks (e.g., BSE beef bans).</li><li style="margin-bottom:1.25rem;"><strong>Pharmaceuticals &amp; Medical Devices:</strong> Must meet regulatory approval: <a href="https://www.fda.gov/" target="_blank" rel="dofollow">FDA</a> (US), <a href="https://www.ema.europa.eu/" target="_blank" rel="dofollow">EMA</a> (EU), MHRA (UK). Importing unapproved drugs is a federal offense in most countries. Personal-use quantities face different rules but are still heavily scrutinized.</li><li style="margin-bottom:1.25rem;"><strong>Chemicals &amp; Hazardous Materials:</strong> Regulated under TSCA (US), REACH (EU), and equivalent frameworks. Require Safety Data Sheets (SDS), proper classification under GHS, and sometimes pre-notification to the importing country's chemical authority.</li><li style="margin-bottom:1.25rem;"><strong>Firearms &amp; Ammunition:</strong> Require ATF import permits (US), or equivalent licensing in other countries. Some nations (Japan, UK, Australia) have near-total bans on civilian firearm imports.</li><li style="margin-bottom:1.25rem;"><strong>Wildlife &amp; Endangered Species:</strong> Regulated under <a href="https://cites.org/" target="_blank" rel="dofollow">CITES (Convention on International Trade in Endangered Species)</a>. Ivory, certain timbers, live exotic animals, and products made from protected species require CITES permits from both exporting and importing countries.</li><li><strong>Electronics &amp; Telecommunications:</strong> Must meet safety/emissions standards: FCC (US), CE/RED (EU), UKCA (UK). Encryption-capable devices may require export/import licenses under the Wassenaar Arrangement.</li></ul>` },
        { id: "sanctions-embargoes", heading: "Trade Sanctions &amp; Embargoes", content: `<p>Sanctions are the most severe form of trade restriction — imposed by governments or international bodies to achieve foreign policy objectives:</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li style="margin-bottom:1rem;"><strong>US (OFAC):</strong> The <a href="https://ofac.treasury.gov/" target="_blank" rel="dofollow">Office of Foreign Assets Control</a> administers comprehensive sanctions against countries (Cuba, North Korea, Iran, Syria) and targeted sanctions against individuals/entities on the SDN list. Violations carry penalties up to $20 million and 30 years imprisonment.</li><li style="margin-bottom:1rem;"><strong>EU:</strong> EU restrictive measures cover arms embargoes, trade restrictions, financial sanctions, and travel bans. Managed through Council Regulations with direct effect across all 27 member states.</li><li style="margin-bottom:1rem;"><strong>UK (OFSI):</strong> The <a href="https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation" target="_blank" rel="dofollow">Office of Financial Sanctions Implementation</a> enforces UK-specific sanctions post-Brexit, which may differ from EU sanctions.</li><li><strong>UN:</strong> UN Security Council sanctions are binding on all member states and typically target specific countries, entities, or individuals involved in threats to peace and security.</li></ul><p style="margin-top:1rem;"><strong>Warning:</strong> Sanctions compliance is <strong>strict liability</strong> in many jurisdictions — meaning ignorance is not a defense. Always screen trading partners against sanctions lists before transacting.</p>` },
        { id: "quotas", heading: "Import Quotas &amp; Tariff-Rate Quotas", content: `<p>Quotas limit the <strong>quantity</strong> or <strong>value</strong> of goods that can be imported:</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li style="margin-bottom:1rem;"><strong>Absolute Quotas:</strong> A hard cap on the quantity of a specific good that can enter. Once the quota is filled, no more can be imported regardless of price or duty paid. Used sparingly but powerfully.</li><li style="margin-bottom:1rem;"><strong>Tariff-Rate Quotas (TRQ):</strong> More common. A lower "in-quota" duty rate applies to imports within the quota volume; a much higher "over-quota" rate applies once the quota is exceeded. Example: US imports of sugar face a 0.625 cents/lb in-quota rate but 15.36 cents/lb over-quota.</li><li><strong>How quotas work:</strong> Quotas typically operate on a "first come, first served" basis. Imports are tracked against the quota; once it's filled, the higher rate applies immediately. This creates a rush to import early in the quota period.</li></ul>` },
        { id: "dual-use", heading: "Dual-Use Export &amp; Import Controls", content: `<p><strong>Dual-use goods</strong> are items that have both civilian and military applications — encryption software, precision machine tools, certain chemicals, nuclear materials, and advanced electronics. These are controlled under multilateral regimes:</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li><strong>Wassenaar Arrangement:</strong> 42 participating states control exports of conventional weapons and dual-use goods/technologies.</li><li><strong>US Export Administration Regulations (EAR):</strong> Administered by the Bureau of Industry and Security (BIS). Goods on the CCL (Commerce Control List) require export licenses. <strong>Note:</strong> US EAR applies extraterritorially — re-exports of US-origin goods also require BIS authorization.</li><li><strong>EU Dual-Use Regulation:</strong> EU Regulation 2021/821 controls exports of dual-use items. Member states issue licenses; the European Commission coordinates the control list.</li></ul><p style="margin-top:1rem;">Dual-use controls affect importers when receiving goods that were exported under license conditions — violating these conditions (e.g., re-exporting to a sanctioned country) constitutes a criminal offense.</p>` },
    ];

    const faqs = [
        { question: "How do I know if my product is restricted?", answer: "Check your destination country's customs authority website for prohibited and restricted goods lists. In the US, CBP maintains a comprehensive list. You can also check product-specific agencies: FDA for food/drugs, EPA for chemicals, CPSC for consumer products, and ATF for firearms." },
        { question: "What happens if I import restricted goods without a license?", answer: "Goods will be seized at the border and may be destroyed at your cost. You may face penalties including fines (often significantly exceeding the goods' value), loss of importing privileges, and in serious cases, criminal prosecution." },
        { question: "Can I import goods from sanctioned countries?", answer: "Generally no. Comprehensive sanctions (Cuba, North Korea, Iran, Syria) prohibit virtually all trade. Targeted sanctions may allow some goods with specific OFAC licenses. Always consult a sanctions compliance specialist before attempting such transactions." },
        { question: "What is a tariff-rate quota?", answer: "A system where a lower duty rate applies to imports within a specified quantity (the 'in-quota' rate), and a much higher rate applies to imports exceeding that quantity (the 'over-quota' rate). Quotas are typically filled on a first-come, first-served basis." },
        { question: "Do import restrictions change frequently?", answer: "Yes. Sanctions can change overnight due to geopolitical events. Product-specific restrictions evolve as regulations update. Disease outbreaks can trigger immediate agricultural import bans. Always verify current restrictions before shipping." },
    ];

    const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) };
    const bcJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": process.env.NEXT_PUBLIC_BASE_URL || "https://duty-decoder.com" }, { "@type": "ListItem", "position": 2, "name": "Import Restrictions" }] };

    return (<>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(bcJsonLd) }} />
        <main style={{ maxWidth: "1100px", margin: "0 auto" }} role="main">
            <header style={{ background: "linear-gradient(135deg, rgba(99,102,241,0.06), rgba(59,130,246,0.04))", border: "1px solid var(--border)", borderRadius: "16px", padding: "clamp(1.5rem, 4vw, 2.5rem) clamp(1.25rem, 4vw, 3rem)", marginBottom: "2rem", textAlign: "center" }}>
                <nav aria-label="Breadcrumb" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", marginBottom: "1rem" }}><Link href="/" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none", fontWeight: 600 }}>Home</Link><span style={{ color: "var(--muted-foreground)", fontSize: "0.85rem" }}>›</span><span style={{ fontSize: "0.85rem", color: "var(--muted-foreground)" }}>Import Restrictions</span></nav>
                <h1 style={{ fontSize: "clamp(1.5rem, 4vw, 2.5rem)", fontWeight: 800, margin: "0 0 1rem", color: "var(--foreground)", lineHeight: 1.2 }}>Import Restrictions — Prohibited Goods, Licensing &amp; Controls</h1>
                <p style={{ fontSize: "1.1rem", color: "var(--muted-foreground)", lineHeight: 1.6, margin: "0 auto", maxWidth: "800px" }}>What you can&apos;t import, what requires licenses, sanctions compliance, quotas, dual-use controls, and how to avoid costly seizures at the border.</p>
            </header>
            <div className="content-sidebar-grid">
                <article aria-label="Import restrictions guide">
                    {sections.map((s, i) => (<section key={`s-${i}`} id={s.id} style={{ ...sS, borderBottom: i < sections.length - 1 ? "1px solid var(--border)" : "none" }}><h2 style={h2}>{s.heading}</h2><div style={body} dangerouslySetInnerHTML={{ __html: s.content }} /></section>))}
                    <div role="banner" style={{ margin: "3rem 0", background: "linear-gradient(135deg, var(--accent), #6366f1)", borderRadius: "16px", padding: "2.5rem", textAlign: "center", boxShadow: "0 10px 30px rgba(99,102,241,0.15)" }}>
                        <h2 style={{ fontSize: "1.75rem", fontWeight: 800, color: "#fff", margin: "0 0 0.75rem" }}>Check Your Import Costs First</h2>
                        <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,0.85)", margin: "0 0 1.5rem" }}>Calculate duties, taxes, and fees for any product before you ship.</p>
                        <Link href="/calculate/" style={{ display: "inline-block", background: "#fff", color: "var(--accent)", fontWeight: 700, padding: "1rem 2.5rem", borderRadius: "8px", textDecoration: "none", fontSize: "1.1rem" }}>Open Calculator →</Link>
                    </div>
                    <section id="faq" aria-label="FAQ" style={{ marginBottom: "3rem" }}><h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "1.5rem", color: "var(--foreground)" }}>Frequently Asked Questions</h2>{faqs.map((f, i) => (<details key={`faq-${i}`} style={{ background: "var(--card)", padding: "1.25rem 1.5rem", borderRadius: "12px", border: "1px solid var(--border)", marginBottom: "0.85rem" }}><summary style={{ fontWeight: 600, cursor: "pointer", color: "var(--foreground)", fontSize: "1rem" }}>{f.question}</summary><div style={{ marginTop: "1rem", color: "var(--muted-foreground)", lineHeight: 1.75, fontSize: "0.95rem" }}>{f.answer}</div></details>))}</section>
                </article>
                <aside aria-label="Quick links" style={{ position: "sticky", top: "100px", display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <section style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.5rem", boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)" }}><h3 style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--foreground)", marginBottom: "0.5rem" }}>Landed Cost Calculator</h3><p style={{ fontSize: "0.9rem", color: "var(--muted-foreground)", marginBottom: "1.25rem", lineHeight: 1.5 }}>Calculate your total import costs.</p><Link href="/calculate/" style={{ display: "block", textAlign: "center", background: "var(--accent)", color: "#fff", fontWeight: 600, padding: "0.85rem 1rem", borderRadius: "8px", textDecoration: "none", fontSize: "0.95rem" }}>Open Calculator →</Link></section>
                    <nav aria-label="Related" style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "1rem" }}>Related Guides</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.6rem" }}><li><Link href="/import-documents/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Documents</Link></li><li><Link href="/customs-clearance/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Customs Clearance</Link></li><li><Link href="/import-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Duty Guide</Link></li><li><Link href="/tariff-rates/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Tariff Rates</Link></li><li><Link href="/hs-code-lookup/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>HS Code Lookup</Link></li></ul></nav>
                    <nav aria-label="Official" style={{ background: "rgba(34,197,94,0.04)", border: "1px solid rgba(34,197,94,0.15)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>Official Sources</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.5rem" }}><li><a href="https://ofac.treasury.gov/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>US OFAC Sanctions ↗</a></li><li><a href="https://www.fda.gov/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>US FDA ↗</a></li><li><a href="https://cites.org/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>CITES Convention ↗</a></li><li><a href="https://www.gov.uk/government/organisations/office-of-financial-sanctions-implementation" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>UK OFSI Sanctions ↗</a></li></ul></nav>
                    <nav aria-label="TOC" style={{ borderTop: "1px solid var(--border)", paddingTop: "1rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>On This Page</h3><ul style={{ listStyle: "none", padding: 0, margin: 0 }}>{sections.map((s, i) => (<li key={`t-${i}`} style={{ marginBottom: "0.4rem" }}><a href={`#${s.id}`} style={{ color: "var(--muted-foreground)", textDecoration: "none", fontSize: "0.85rem" }}>{s.heading}</a></li>))}<li style={{ marginTop: "0.75rem", paddingTop: "0.75rem", borderTop: "1px solid var(--border)" }}><a href="#faq" style={{ color: "var(--foreground)", fontWeight: 500, textDecoration: "none", fontSize: "0.85rem" }}>FAQs</a></li></ul></nav>
                </aside>
            </div>
        </main>
    </>);
}
