-- ============================================================
-- 011_guide_html.sql
-- Add longform HTML guide column to landed_costs
-- Generated by the Duty Guide upgrade pipeline
-- ============================================================

ALTER TABLE "public"."landed_costs"
ADD COLUMN IF NOT EXISTS guide_html TEXT,
ADD COLUMN IF NOT EXISTS guide_meta_description TEXT;

COMMENT ON COLUMN public.landed_costs.guide_html IS 'Complete longform HTML import duty guide generated by the 3-step AI pipeline (Research → Write → Validate). Contains full H2/H3/H4 heading hierarchy, FAQs, and disclaimer.';
COMMENT ON COLUMN public.landed_costs.guide_meta_description IS 'SEO meta description (150-160 chars) extracted from the guide generation pipeline.';
