import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Customs Clearance Explained — Process, Documents & Timelines 2026 | DutyDecoder",
    description: "Step-by-step customs clearance guide: how goods clear customs, required documents, customs broker role, inspection procedures, and how to avoid costly delays at the border.",
    alternates: { canonical: "/customs-clearance/" },
    keywords: ["customs clearance", "customs clearance process", "how to clear customs", "customs broker", "customs inspection", "customs declaration", "import clearance", "border clearance 2026"],
    openGraph: { title: "Customs Clearance — Step-by-Step Import Clearance Guide", description: "The complete customs clearance process: pre-arrival filing, documentation, classification, inspection, duty payment, and goods release.", url: "/customs-clearance", type: "article" },
};

export default function CustomsClearancePage() {
    const sS: React.CSSProperties = { marginBottom: "2.5rem", paddingBottom: "2.5rem", borderBottom: "1px solid var(--border)" };
    const h2: React.CSSProperties = { fontSize: "1.5rem", fontWeight: 700, marginBottom: "1rem", color: "var(--foreground)" };
    const body: React.CSSProperties = { color: "var(--muted-foreground)", lineHeight: 1.85, fontSize: "1.05rem" };

    const sections = [
        { id: "what-is-customs-clearance", heading: "What Is Customs Clearance?", content: `<strong>Customs clearance</strong> is the formal process of getting imported goods through a country's customs authority so they can enter domestic commerce. Every shipment crossing an international border — whether a single parcel or a 40-foot container — must be declared, inspected (if selected), assessed for duties and taxes, and officially released.<p style="margin-top:1rem;">The process is managed by customs authorities like <a href="https://www.cbp.gov/" target="_blank" rel="dofollow">U.S. CBP</a>, <a href="https://www.gov.uk/government/organisations/hm-revenue-customs" target="_blank" rel="dofollow">UK HMRC</a>, or the <a href="https://www.cbsa-asfc.gc.ca/" target="_blank" rel="dofollow">Canada CBSA</a>. Failure to clear customs properly can result in shipment holds, penalties, or seizure of goods.</p>` },
        { id: "clearance-steps", heading: "The Customs Clearance Process (Step-by-Step)", content: `<ol style="padding-left:1.5rem;"><li style="margin-bottom:1.25rem;"><strong>Pre-Arrival Filing:</strong> Before goods arrive, the importer or broker submits an advance cargo declaration. In the US, this is the <a href="https://www.cbp.gov/trade/acs/ace" target="_blank" rel="dofollow">ACE (Automated Commercial Environment)</a> filing, due 24 hours before vessel loading. The EU requires an ENS (Entry Summary Declaration) via the ICS2 system.</li><li style="margin-bottom:1.25rem;"><strong>Cargo Arrival &amp; Manifest Review:</strong> When the vessel/aircraft arrives, customs matches manifest data against advance filings. Discrepancies trigger holds.</li><li style="margin-bottom:1.25rem;"><strong>Import Declaration Filing:</strong> The importer of record (or their customs broker) files the formal import declaration containing: product description, <a href="/hs-code-lookup/">HS code</a>, country of origin, customs value, and supporting documents.</li><li style="margin-bottom:1.25rem;"><strong>Risk Assessment &amp; Inspection:</strong> Customs runs automated risk scoring. Low-risk shipments proceed directly; flagged shipments undergo document review or physical inspection (X-ray, sampling, or full container exam).</li><li style="margin-bottom:1.25rem;"><strong>Duty &amp; Tax Assessment:</strong> Customs calculates applicable <a href="/import-duty/">duties</a> and <a href="/import-tax/">taxes</a> based on the declared classification and value.</li><li style="margin-bottom:1.25rem;"><strong>Payment &amp; Release:</strong> Once duties are paid (or secured by a customs bond), goods are released from customs control. The importer receives clearance authorization.</li><li><strong>Post-Clearance Audit:</strong> Customs retains the right to audit declarations for up to 5 years. Importers must keep all supporting documentation.</li></ol>` },
        { id: "documents-needed", heading: "Documents Required for Customs Clearance", content: `<p>Missing or incorrect documentation is the #1 cause of clearance delays. The essential documents are:</p><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem;margin:1.5rem 0;"><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Commercial Invoice</strong><p style="font-size:0.9rem;margin:0;">The primary valuation document. Must include seller/buyer details, product description, quantity, unit price, total value, Incoterms, and currency.</p></div><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Bill of Lading (B/L)</strong><p style="font-size:0.9rem;margin:0;">Transport contract document. Sea freight uses B/L; air freight uses Air Waybill (AWB). Proves ownership and transport terms.</p></div><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Packing List</strong><p style="font-size:0.9rem;margin:0;">Details the physical contents: number of packages, dimensions, weight, and contents of each package. Customs uses this for inspection verification.</p></div><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Certificate of Origin</strong><p style="font-size:0.9rem;margin:0;">Proves where goods were manufactured. Required for FTA preferential rates. Must be issued by an authorized body in the exporting country.</p></div><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Import License (if required)</strong><p style="font-size:0.9rem;margin:0;">Certain goods (firearms, pharmaceuticals, food, chemicals) require prior approval from regulatory agencies before importation.</p></div><div style="background:rgba(99,102,241,0.05);border:1px solid var(--border);border-radius:12px;padding:1.25rem;"><strong style="display:block;color:var(--accent);margin-bottom:0.5rem;">Customs Bond (US)</strong><p style="font-size:0.9rem;margin:0;">Financial guarantee ensuring duties will be paid. Required for all US commercial imports over $2,500. Available as single-entry or continuous bonds.</p></div></div><p>For a comprehensive list, see our <a href="/import-documents/">Import Documents Guide</a>.</p>` },
        { id: "customs-broker", heading: "Do You Need a Customs Broker?", content: `<p>A <strong>customs broker</strong> is a licensed professional who files import declarations, calculates duties, and navigates regulatory requirements on behalf of importers. While not legally required in every country, using a broker is strongly recommended for:</p><ul style="padding-left:1.5rem;margin-top:1rem;"><li><strong>Commercial shipments:</strong> Brokers have direct electronic connectivity with customs systems (ACE in the US, CHIEF/CDS in the UK) for fast filing.</li><li><strong>Complex classifications:</strong> Products that could fall under multiple HS codes benefit from a broker's classification expertise.</li><li><strong>Regulated goods:</strong> Food, drugs, chemicals, and electronics require coordination with multiple agencies (FDA, CPSC, EPA in the US).</li><li><strong>High-value shipments:</strong> The cost of a broker ($100–$300 per entry) is trivial compared to the risk of classification penalties on a $500K shipment.</li></ul><p style="margin-top:1rem;">In the US, customs brokers must pass the <a href="https://www.cbp.gov/trade/programs-administration/customs-brokers" target="_blank" rel="dofollow">CBP-administered licensing exam</a> — one of the most difficult professional exams in trade, with a pass rate typically under 15%.</p>` },
        { id: "timelines", heading: "Customs Clearance Timelines", content: `<div style="overflow-x:auto;margin:1rem 0;"><table style="width:100%;border-collapse:collapse;font-size:0.95rem;"><thead><tr style="border-bottom:2px solid var(--border);"><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Scenario</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Typical Timeline</th><th style="text-align:left;padding:0.75rem;color:var(--foreground);font-weight:700;">Key Factor</th></tr></thead><tbody><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Standard clearance (no issues)</td><td style="padding:0.75rem;"><strong>1–3 days</strong></td><td style="padding:0.75rem;">All documents correct, no inspection</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Document review only</td><td style="padding:0.75rem;"><strong>3–5 days</strong></td><td style="padding:0.75rem;">Customs requests additional documentation</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Physical inspection</td><td style="padding:0.75rem;"><strong>5–14 days</strong></td><td style="padding:0.75rem;">Container moved to exam station, opened, and re-sealed</td></tr><tr style="border-bottom:1px solid var(--border);"><td style="padding:0.75rem;">Classification dispute</td><td style="padding:0.75rem;"><strong>2–8 weeks</strong></td><td style="padding:0.75rem;">Customs disagrees with declared HS code; formal review required</td></tr><tr><td style="padding:0.75rem;">Regulatory hold (FDA, CPSC, etc.)</td><td style="padding:0.75rem;"><strong>1–6 weeks</strong></td><td style="padding:0.75rem;">Goods subject to other agency review or testing</td></tr></tbody></table></div>` },
        { id: "common-delays", heading: "Common Causes of Clearance Delays", content: `<ul style="padding-left:1.5rem;"><li style="margin-bottom:1rem;"><strong>Incomplete or inconsistent documentation:</strong> Mismatched values between the invoice and declaration, missing packing lists, or unsigned certificates of origin. Always ensure documents are cross-verified before filing.</li><li style="margin-bottom:1rem;"><strong>Incorrect HS code classification:</strong> Customs will hold goods if the declared code doesn't match the physical product. Use our <a href="/hs-code-finder/">AI HS Code Finder</a> to validate before shipping.</li><li style="margin-bottom:1rem;"><strong>Customs exam selection:</strong> Approximately 3-5% of shipments are selected for physical inspection. This is largely random but influenced by risk profiling (new importers, high-risk origins, anomalous values).</li><li style="margin-bottom:1rem;"><strong>Regulatory agency holds:</strong> Food (FDA), consumer products (CPSC), alcohol/tobacco (TTB), and chemicals (EPA) all have separate clearance requirements that run parallel to customs.</li><li style="margin-bottom:1rem;"><strong>Anti-dumping/CVD orders:</strong> If your goods are subject to AD/CVD orders, additional documentation (certificates, scope rulings) is required before release.</li><li><strong>Customs bond issues:</strong> Insufficient bond coverage or expired bonds will prevent release until a new bond is filed.</li></ul>` },
    ];

    const faqs = [
        { question: "How long does customs clearance take?", answer: "Standard clearance with correct documentation takes 1-3 days. Physical inspections add 5-14 days. Classification disputes or regulatory holds can extend clearance to several weeks." },
        { question: "Can I clear customs without a broker?", answer: "Yes, self-filing is technically possible in most countries. However, the complexity of tariff classification, multi-agency compliance, and electronic filing systems makes it impractical for most commercial importers." },
        { question: "What happens if my shipment is inspected?", answer: "Your container is moved to an exam station, physically opened, and inspected by customs officers. You pay for the exam (typically $300-$1,000+ in the US) plus any demurrage/storage charges while the container is held." },
        { question: "What causes customs to flag a shipment?", answer: "Risk factors include: new importer with no import history, high-risk countries of origin, anomalous declared values (too high or too low), incomplete documentation, and random selection as part of compliance programs." },
        { question: "Do I need a customs bond?", answer: "In the US, a customs bond is required for all commercial shipments valued over $2,500. A continuous bond (~$500/year) covers unlimited entries; a single-entry bond covers one shipment. Most countries have equivalent financial guarantee requirements." },
    ];

    const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", "mainEntity": faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) };
    const bcJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{ "@type": "ListItem", "position": 1, "name": "Home", "item": process.env.NEXT_PUBLIC_BASE_URL || "https://duty-decoder.com" }, { "@type": "ListItem", "position": 2, "name": "Customs Clearance" }] };

    return (<>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(bcJsonLd) }} />
        <main style={{ maxWidth: "1100px", margin: "0 auto" }} role="main">
            <header style={{ background: "linear-gradient(135deg, rgba(99,102,241,0.06), rgba(59,130,246,0.04))", border: "1px solid var(--border)", borderRadius: "16px", padding: "clamp(1.5rem, 4vw, 2.5rem) clamp(1.25rem, 4vw, 3rem)", marginBottom: "2rem", textAlign: "center" }}>
                <nav aria-label="Breadcrumb" style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: "0.5rem", marginBottom: "1rem" }}><Link href="/" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none", fontWeight: 600 }}>Home</Link><span style={{ color: "var(--muted-foreground)", fontSize: "0.85rem" }}>›</span><span style={{ fontSize: "0.85rem", color: "var(--muted-foreground)" }}>Customs Clearance</span></nav>
                <h1 style={{ fontSize: "clamp(1.5rem, 4vw, 2.5rem)", fontWeight: 800, margin: "0 0 1rem", color: "var(--foreground)", lineHeight: 1.2 }}>Customs Clearance — Step-by-Step Import Clearance Guide</h1>
                <p style={{ fontSize: "1.1rem", color: "var(--muted-foreground)", lineHeight: 1.6, margin: "0 auto", maxWidth: "800px" }}>How goods clear customs: from pre-arrival filing and documentation to inspection, duty payment, and release. Plus common causes of delays and how to avoid them.</p>
            </header>
            <div className="content-sidebar-grid">
                <article aria-label="Customs clearance guide">
                    {sections.map((s, i) => (<section key={`s-${i}`} id={s.id} style={{ ...sS, borderBottom: i < sections.length - 1 ? "1px solid var(--border)" : "none" }}><h2 style={h2}>{s.heading}</h2><div style={body} dangerouslySetInnerHTML={{ __html: s.content }} /></section>))}
                    <div role="banner" style={{ margin: "3rem 0", background: "linear-gradient(135deg, var(--accent), #6366f1)", borderRadius: "16px", padding: "2.5rem", textAlign: "center", boxShadow: "0 10px 30px rgba(99,102,241,0.15)" }}>
                        <h2 style={{ fontSize: "1.75rem", fontWeight: 800, color: "#fff", margin: "0 0 0.75rem" }}>Know Your Costs Before Shipping</h2>
                        <p style={{ fontSize: "1.05rem", color: "rgba(255,255,255,0.85)", margin: "0 0 1.5rem" }}>Calculate exact duties, taxes, and fees before your goods reach the border.</p>
                        <Link href="/calculate/" style={{ display: "inline-block", background: "#fff", color: "var(--accent)", fontWeight: 700, padding: "1rem 2.5rem", borderRadius: "8px", textDecoration: "none", fontSize: "1.1rem" }}>Open Calculator →</Link>
                    </div>
                    <section id="faq" aria-label="FAQ" style={{ marginBottom: "3rem" }}><h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "1.5rem", color: "var(--foreground)" }}>Frequently Asked Questions</h2>
                        {faqs.map((f, i) => (<details key={`faq-${i}`} style={{ background: "var(--card)", padding: "1.25rem 1.5rem", borderRadius: "12px", border: "1px solid var(--border)", marginBottom: "0.85rem" }}><summary style={{ fontWeight: 600, cursor: "pointer", color: "var(--foreground)", fontSize: "1rem" }}>{f.question}</summary><div style={{ marginTop: "1rem", color: "var(--muted-foreground)", lineHeight: 1.75, fontSize: "0.95rem" }}>{f.answer}</div></details>))}
                    </section>
                </article>
                <aside aria-label="Quick links" style={{ position: "sticky", top: "100px", display: "flex", flexDirection: "column", gap: "1.5rem" }}>
                    <section style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.5rem", boxShadow: "0 4px 6px -1px rgba(0,0,0,0.1)" }}><h3 style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--foreground)", marginBottom: "0.5rem" }}>Landed Cost Calculator</h3><p style={{ fontSize: "0.9rem", color: "var(--muted-foreground)", marginBottom: "1.25rem", lineHeight: 1.5 }}>Know your total import costs before goods ship.</p><Link href="/calculate/" style={{ display: "block", textAlign: "center", background: "var(--accent)", color: "#fff", fontWeight: 600, padding: "0.85rem 1rem", borderRadius: "8px", textDecoration: "none", fontSize: "0.95rem" }}>Open Calculator →</Link></section>
                    <nav aria-label="Related" style={{ background: "var(--card)", border: "1px solid var(--border)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "1rem" }}>Related Guides</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.6rem" }}><li><Link href="/import-documents/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Documents</Link></li><li><Link href="/import-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Duty Guide</Link></li><li><Link href="/import-restrictions/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Import Restrictions</Link></li><li><Link href="/customs-duty/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>Customs Duty</Link></li><li><Link href="/hs-code-lookup/" style={{ fontSize: "0.9rem", color: "var(--accent)", textDecoration: "none" }}>HS Code Lookup</Link></li></ul></nav>
                    <nav aria-label="Official sources" style={{ background: "rgba(34,197,94,0.04)", border: "1px solid rgba(34,197,94,0.15)", borderRadius: "12px", padding: "1.25rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>Official Sources</h3><ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.5rem" }}><li><a href="https://www.cbp.gov/trade/acs/ace" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>US CBP ACE Portal ↗</a></li><li><a href="https://www.cbp.gov/trade/programs-administration/customs-brokers" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>CBP Broker Licensing ↗</a></li><li><a href="https://www.cbsa-asfc.gc.ca/" target="_blank" rel="dofollow" style={{ fontSize: "0.85rem", color: "var(--accent)", textDecoration: "none" }}>Canada CBSA ↗</a></li></ul></nav>
                    <nav aria-label="TOC" style={{ borderTop: "1px solid var(--border)", paddingTop: "1rem" }}><h3 style={{ fontSize: "0.8rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.05em", color: "var(--muted-foreground)", marginBottom: "0.75rem" }}>On This Page</h3><ul style={{ listStyle: "none", padding: 0, margin: 0 }}>{sections.map((s, i) => (<li key={`t-${i}`} style={{ marginBottom: "0.4rem" }}><a href={`#${s.id}`} style={{ color: "var(--muted-foreground)", textDecoration: "none", fontSize: "0.85rem" }}>{s.heading}</a></li>))}<li style={{ marginTop: "0.75rem", paddingTop: "0.75rem", borderTop: "1px solid var(--border)" }}><a href="#faq" style={{ color: "var(--foreground)", fontWeight: 500, textDecoration: "none", fontSize: "0.85rem" }}>FAQs</a></li></ul></nav>
                </aside>
            </div>
        </main>
    </>);
}
